### PR TITLE
SG-29856 Replace shotgunsoftware references

### PR DESCRIPTION
**Pull request by carlos-villavicencio-adsk**

### CODE REVIEW

**Comment by carlos-villavicencio-adsk** [comment]
@julien-lang can you approve this PR, please?

**Review by julien-lang — APPROVED** [review]
LGTM!
However, I think we should archive this repository.

**Comment by carlos-villavicencio-adsk** [comment]
I don't have merge access for this anyway. I'll appreciate it if you do it (or archive it afterwards)

**Comment by julien-lang** [comment]
Closing this PR as we decided to archive the repository.

**Pull request closed without merging**
